### PR TITLE
Fix Internal Server Error when nonexistent timeseries

### LINKED ISSUE #76: Internal server error when accessing nonexistent timeseries
(http://main.hydroscope.gr/timeseries/data/) (?object_id=11)

In views.py, line 643: DoesNotExist

### PR DESCRIPTION
**Pull request by kickapoo**

### CODE REVIEW

**Comment by kickapoo** [comment]
- [ ] Add expect DoesNotExist

**Comment by kickapoo** [comment]
@aptiko Please revisit

**Comment by aptiko** [comment]
I think you don't need `ObjectDoesNotExist`; isn't `Timeseries.DoesNotExist` sufficient?

**Comment by kickapoo** [comment]
@aptiko 

Please comment me what is more needed for this PR.

**Comment by aptiko** [comment]
Please use `Timeseries.DoesNotExist` instead of `ObjectDoesNotExist`.

**Comment by kickapoo** [comment]
@aptiko Updated using `Timeseries.DoesNotExist`

**Comment by kickapoo** [comment]
@aptiko Please revisit

**Comment by aptiko** [comment]
Merged.

**Pull request closed without merging**
